version: "2.1"

services:
  build-slides:
    image: asciidoctor/docker-asciidoctor:latest
    volumes:
    - ./:/documents
    command: asciidoctor-revealjs -D /documents/docs -o slides.html /documents/slides.adoc
